apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 761018861517.dkr.ecr.us-east-1.amazonaws.com/devops-project:latest
          ports:
            - containerPort: 8080
