apiVersion: v1
kind: Service
metadata:
  name: devops-webapp-service
  labels:
    app: devops-webapp
spec:
  type: LoadBalancer
  selector:
    app: devops-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
